"""Port all native ActiveBlock branches, including Ready and hover noise.

Only input/sampler/output plumbing changes. Native mediump/highp intermediates,
operation order, and constants remain intact. Packed masks avoid exceeding the
macroquad texture cache. Run from any directory; official extraction is read-only.
"""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[3]
destination = root / "phira/prpr/src/core/block_shader_full.frag"
source = (root / "_official_src/shader_code/Unlit_ActiveBlock.p0.txt").read_text()
fragment = source.split("#ifdef FRAGMENT", 1)[1]
uniforms = "\n".join(line for line in fragment.splitlines() if line.startswith("uniform") and "sampler" not in line)
temps = fragment[fragment.index("vec4 u_xlat0;"):fragment.index("void main()")]
body = fragment[fragment.index("{", fragment.index("void main()")) + 1:fragment.rfind("}\n")]

# These native samples have distinct filtering and coordinate spaces. Compose
# and disabled/Ready masks use chart-local UV; hover and scene color use screen UV.
for old, new in {
    "texture(_ComposeRT, vs_TEXCOORD0.xy).x": "composeSample(fieldUV)",
    "texture(_EffectRT, u_xlat16.xy).x": "effectSample(u_xlat16.xy).x",
    "texture(_EffectRT, vs_TEXCOORD0.xy).y": "effectSample(fieldUV).y",
    "texture(_DisabledNormalBlockRT, vs_TEXCOORD0.xy).x": "auxSample(fieldUV).r",
    "texture(_DisabledSubtractBlockRT, vs_TEXCOORD0.xy).y": "auxSample(fieldUV).g",
    "texture(_ReadyComposeRT, vs_TEXCOORD0.xy).x": "auxSample(fieldUV).b",
    "texture(_TouchHoverRT, vs_TEXCOORD0.xy).x": "hoverSample(sceneUV)",
    "textureLod(_TouchHoverRT, u_xlat0.xy, 0.0).x": "hoverSample(u_xlat0.xy)",
    "texture(_SceneColor, u_xlat16.xy).xyz": "snapshotSample(u_xlat16.xy).xyz",
    "u_xlat33.xy = vs_TEXCOORD0.xy * _ScreenParams.xy;": "u_xlat33.xy = sceneUV.xy * _ScreenParams.xy;",
    "u_xlat0.xy = u_xlat0.xy * vec2(vec2(_TouchDisplaceStrength, _TouchDisplaceStrength)) + vs_TEXCOORD0.xy;":
        "u_xlat0.xy = u_xlat0.xy * vec2(vec2(_TouchDisplaceStrength, _TouchDisplaceStrength)) + sceneUV.xy;",
}.items():
    assert old in body, old
    body = body.replace(old, new)
for old, new in {
    "_Time": "uUnityTime", "vs_TEXCOORD0": "fieldUV", "vs_TEXCOORD1": "displaceUV",
    "vs_TEXCOORD2": "sparkUV", "vs_TEXCOORD3": "screenPos", "vs_TEXCOORD4": "touchDisplaceUV",
    "vs_TEXCOORD5": "noiseUV", "vs_TEXCOORD6": "clipHalfWidth", "_DisplaceMap,": "uDisplaceTex,",
    "_SparkMap,": "uSparkTex,", "_TouchDisplaceMap,": "uDisplaceTex,", "_NoiseMap,": "uNoiseTex,",
    "SV_Target0": "result", "texture(": "texture2D(", "return;": "return result;",
}.items():
    body = body.replace(old, new)
    uniforms = uniforms.replace(old, new)
# The official textures have no mipmaps. The GLES2 base-level sample matches
# native textureLod(..., 0) without requiring a shader_texture_lod extension.
body = re.sub(r"textureLod\((u(?:Displace|Noise)Tex), ([^\n]*?), 0\.0\)", r"texture2D(\1, \2)", body)
assert "textureLod" not in body
# ActiveBlock uses One / OneMinusSrcAlpha. Ready and hover contribute additive
# RGB without changing alpha, exactly as in the native fragment's final lines.
# Keeping the full native output together avoids either losing these terms in
# a straight-alpha pipeline or applying the Ready material a second time.

disabled = (root / "_official_src/shader_code/Unlit_DisabledBlock.p0.txt").read_text().split("#ifdef FRAGMENT", 1)[1]
disabled_temps = disabled[disabled.index("mediump float u_xlat16_0;"):disabled.index("void main()")]
disabled_body = disabled[disabled.index("{", disabled.index("void main()")) + 1:disabled.rfind("}\n")]
disabled_body = disabled_body.replace("u_xlat16_0 = texture(_ComposeRT, vs_TEXCOORD0.xy).x;", "u_xlat16_0 = mask;")
disabled_uniforms = "\n".join(line for line in disabled.splitlines() if line.startswith("uniform") and any(name in line for name in (
    "_FillColor", "_FillOpacity", "_SparkTint", "_SparkMapOpacity", "_SparkDisplaceIntensity", "_DisplaceSpeed")))
for old, new in {
    "_FillColor": "uDisabledFillColor", "_FillOpacity": "uDisabledFillOpacity", "_SparkTint": "uDisabledSparkTint",
    "_SparkMapOpacity": "uDisabledSparkOpacity", "_SparkDisplaceIntensity": "uDisabledSparkIntensity",
    "_DisplaceSpeed": "uDisabledSpeed", "_Time": "uUnityTime", "vs_TEXCOORD2": "disabledDisplaceUV",
    "vs_TEXCOORD3": "sparkUV", "vs_COLOR0.w": "1.0", "_DisplaceMap,": "uDisplaceTex,", "_SparkMap,": "uSparkTex,",
    "texture(": "texture2D(", "SV_Target0": "result", "return;": "return result;",
}.items():
    disabled_body = disabled_body.replace(old, new)
    disabled_uniforms = disabled_uniforms.replace(old, new)

header = """#version 100
// Generated by docs/block-area/build_full_fragment.py. Native operation order
// and precision are retained for all ActiveBlock, Ready and hover SDF terms.
precision highp float;
precision highp int;
varying lowp vec4 color;
varying highp vec2 fieldUV;
varying highp vec2 sceneUV;
varying highp vec2 displaceUV;
varying highp vec2 sparkUV;
varying highp vec2 disabledDisplaceUV;
varying highp vec2 touchDisplaceUV;
varying highp vec2 noiseUV;
varying highp vec4 screenPos;
varying highp float clipHalfWidth;
uniform int uLayer;
uniform mediump sampler2D uDisplaceTex;
uniform mediump sampler2D uSparkTex;
uniform mediump sampler2D uMasks;
uniform mediump sampler2D uScene;
uniform mediump sampler2D uAuxMasks;
uniform mediump sampler2D uNoiseTex;
vec4 snapshotSample(vec2 uv);
float composeSample(vec2 uv);
vec2 effectSample(vec2 uv);
vec4 auxSample(vec2 uv);
float hoverSample(vec2 uv);
"""
helpers = """
vec2 basePixelUV(vec2 uv) {
    vec2 size = _EffectRT_TexelSize.zw * 0.5;
    return (floor(uv * size) + 0.5) / size;
}
float composeSample(vec2 uv) { return texture2D(uMasks, basePixelUV(uv)).r; }
vec2 effectSample(vec2 uv) { return texture2D(uMasks, uv).gb; }
vec4 auxSample(vec2 uv) { return texture2D(uAuxMasks, basePixelUV(uv)); }
float hoverSample(vec2 uv) { return texture2D(uAuxMasks, basePixelUV(uv)).a; }
vec4 snapshotSample(vec2 uv) {
    vec2 size = max(floor(_ScreenParams.xy / 3.0), vec2(1.0));
    uv = (floor(clamp(uv, 0.0, 1.0) * size) + 0.5) / size;
    return texture2D(uScene, uv);
}
void main() {
    // uMasks RGBA=(active Compose, Edge, Glow, disabled Compose).
    // uAuxMasks RGB=(ready-only Normal.r, ready-only Subtract.g, composedDisabled.r),
    // A=hover mask in SCREEN UV, independently of the chart model's flips.
    if (uLayer == 0) {
        float disabledMask = texture2D(uMasks, basePixelUV(fieldUV)).a;
        gl_FragColor = disabledColor(disabledMask) * color;
    } else {
        gl_FragColor = fullActive() * color;
    }
}
"""
disabled_function = "vec4 disabledColor(mediump float mask) {\n    vec4 result;\n" + disabled_temps + disabled_body + "\n}\n"
full_function = "vec4 fullActive() {\n    vec4 result;\n" + body + "\n}\n"
destination.write_text(header + uniforms + "\n" + disabled_uniforms + "\n" + temps + disabled_function + full_function + helpers)
print(destination)
